function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    params(5)=(1-params(1)*(1-params(2)))/params(1);
    params(7)=params(2)*params(9)*(params(11)-1)/params(11)*1/params(5);
    params(6)=1-params(7);
    % Auxiliary equations
end
